## Homework 14 by: **Muhammad Galang Gardamukti**

In [ ]:
import numpy as np
base = np.array([10,10,20,20,30,30,40,10,15,15,12,20,30])
print(base)

[10 10 20 20 30 30 40 10 15 15 12 20 30]


### **Distinct Values**

In [ ]:
distinct = np.unique(base)
print('Value yang unik dari array:')
print(distinct)

Value yang unik dari array:
[10 12 15 20 30 40]


### **Index from Distinct Values**

In [8]:
distinct, index = np.unique(base, return_index=True)
print(index)

[ 0 10  8  2  4  6]


### **Sub-Array Division**

In [ ]:
split = np.split(distinct, [3])
print(split)

[array([10, 12, 15]), array([20, 30, 40])]
